[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["format", "-"] }

[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixfmt", args = ["-"] }

[[language]]
name = "haskell"
language-servers = ["haskell-language-server"]
auto-format = true

[[language]]
name = "elixir"
language-servers = ["expert", "elixir-ls"]
auto-format = true

[[language]]
name = "heex"
language-servers = ["expert", "elixir-ls"]

[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[[language]]
name = "javascript"
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
]
auto-format = true

[[language]]
name = "typescript"
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
]
auto-format = true

[[language]]
name = "tsx"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
]

[[language]]
name = "jsx"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
]

[[language]]
name = "rust"
auto-format = true
formatter = { command = "rustfmt" }

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "json"
language-servers = [
  { name = "vscode-json-language-server", except-features = [
    "format",
  ] },
  "biome",
]
